name: nutmeg
channels:
  - conda-forge
dependencies:
  - python=3.14
  - pytest
  - pip
  - pip:
      - redis
      - fastmcp
      - httpx
      - fakeredis
      - lupa
      - fastapi
      - uvicorn
